include:
  - template: Auto-DevOps.gitlab-ci.yml


stages:
  - build
  - deploy_test
  - test
  - deploy  # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

# pipeline configuration variables (i.e. not secrets) are better kept in git for transparency
variables:
  AUTO_DEVOPS_DEPLOY_DEBUG: 1
  TEST_DISABLED: 1
  SECRET_DETECTION_DISABLED: 1

# override production_manual from Auto DevOps to include the tiller.log artifact
production_manual:
  artifacts:
    paths: [environment_url.txt, tiller.log]
    when: always



# additional, non-Auto DevOps jobs

test_environment:
  stage: deploy-testing
  script:
    - echo "deply..."

regressions:
  stage: test
  script:
    - echo "test..."

functional tests:
  stage: test
  script:
    - echo "test..."

mobile tests:
  stage: test
  script:
    - echo "test..."

