include:
  - template: Auto-DevOps.gitlab-ci.yml


stages:
  - build
  - deploy-testing
  - validate-environment
  - test
  - deploy  # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup


test-environment:
  stage: deploy-testing
  script:
    - echo "deply..."

ping-environment:
  stage: validate-environment
  script:
    - echo "deply..."


regressions:
  stage: test
  script:
    - echo "test..."

functional tests:
  stage: test
  script:
    - echo "test..."

mobile tests:
  stage: test
  script:
    - echo "test..."

