include:
  - template: Auto-DevOps.gitlab-ci.yml


stages:
  - build
  - deploy-testing
  - validate-environment
  - test
  - deploy 
  - review
  - cleanup

# pipeline configuration variables (i.e. not secrets) are better kept in git for transparency
variables:
  AUTO_DEVOPS_DEPLOY_DEBUG: 1
  TEST_DISABLED: 1
  SECRET_DETECTION_DISABLED: 1

# override production_manual from Auto DevOps to include the tiller.log artifact
production_manual:
  artifacts:
    paths: [environment_url.txt, tiller.log]
    when: always



# additional, non-Auto DevOps jobs

test-environment:
  stage: deploy-testing
  script:
    - echo "deply..."

ping-environment:
  stage: validate-environment
  script:
    - echo "deply..."


regressions:
  stage: test
  script:
    - echo "test..."

functional tests:
  stage: test
  script:
    - echo "test..."

mobile tests:
  stage: test
  script:
    - echo "test..."

